<?php
// (c) Copyright by meindlSOFT, 2005.
// File: lang/german.inc
// English language definitions: cphplib
//

define('STR_AT', 'at');
define('STR_YESTERDAY', 'Yesterday');
define('STR_TODAY', 'Today');
define('STR_TOMORROW', 'Tomorrow');
define('STR_ACCESS_DENIED', 'Access denied');
define('STR_CHARACTER_SET', 'iso-8859-1');
define('STR_FORM_ERROR_HEADER', 'The following errors occured');

define('STR_PAGE_FIRST', 'First page');
define('STR_PAGE_LAST', 'Last page');
define('STR_PAGE_NEXT', 'Next page');
define('STR_PAGE_PREV', 'Previous page');

define('STR_DATE', 'Date');
define('STR_TIME', 'Time');

define('STR_SORT_ASC', 'Ascending sorting');
define('STR_SORT_DESC', 'Descending sorting');

?>
