<?php
// (c) Copyright by meindlSOFT, 2005.
// File: lang/german.inc
// English language definitions: cphplib
//

define('STR_AT', 'um');
define('STR_YESTERDAY', 'Gestern');
define('STR_TODAY', 'Heute');
define('STR_TOMORROW', 'Morgen');
define('STR_ACCESS_DENIED', 'Zugriff verboten');
define('STR_CHARACTER_SET', 'iso-8859-15');
define('STR_FORM_ERROR_HEADER', 'Folgende Fehler sind aufgetreten');

define('STR_PAGE_NEXT', "N&auml;chste Seite");
define('STR_PAGE_LAST', "Letzte Seite");
define('STR_PAGE_PREV', "Vorherige Seite");
define('STR_PAGE_FIRST', "Erste Seite");

define('STR_DATE', 'Datum');
define('STR_TIME', 'Zeit');

define('STR_SORT_ASC', 'Aufsteigend sortieren');
define('STR_SORT_DESC', 'Absteigend sortieren');

?>
